# 代理服务器配置文件
host: ""
port: 8317
tls:
  enable: false
  cert: ""
  key: ""
remote-management:
  allow-remote: true
  secret-key: "$"
  disable-control-panel: false
  panel-github-repository: "https://github.com/router-for-me/Cli-Proxy-API-Management-Center"
auth-dir: "~/.cli-proxy-api"
api-keys:
  - "sk-1"
  - "sk-2"
  - "sk-3"
debug: false
commercial-mode: false
logging-to-file: false
logs-max-total-size-mb: 0
usage-statistics-enabled: false
proxy-url: ""
force-model-prefix: false
request-retry: 3
max-retry-interval: 30
quota-exceeded:
  switch-project: true
  switch-preview-model: true
routing:
  strategy: "round-robin"
ws-auth: true
nonstream-keepalive-interval: 0
codex-instructions-enabled: false
oauth-model-alias:
  antigravity:
    - name: "rev19-uic3-1p"
      alias: "gemini-2.5-computer-use-preview-10-2025"
      fork: true
    - name: "gemini-3-pro-image"
      alias: "gemini-3-pro-image"
      fork: true
    - name: "gemini-3-pro-high"
      alias: "gemini-3-pro-high"
      fork: true
    - name: "gemini-3-flash"
      alias: "gemini-3-flash-preview"
      fork: true
    - name: "claude-sonnet-4-5"
      alias: "claude-sonnet-4-5"
      fork: true
    - name: "claude-sonnet-4-5-thinking"
      alias: "claude-sonnet-4-5-20250514"
      fork: true
    - name: "claude-opus-4-5-thinking"
      alias: "claude-opus-4-5-20251101"
      fork: true
    - name: "gemini-2.5-flash"
    - name: "gemini-2.5-flash-lite"
    - name: "gpt-oss-120b-medium"
  codex:
    - name: "gpt-5"
    - name: "gpt-5-codex"
    - name: "gpt-5-codex-mini"
    - name: "gpt-5.1"
    - name: "gpt-5.1-codex"
    - name: "gpt-5.1-codex-max"
    - name: "gpt-5.1-codex-mini"
    - name: "gpt-5.2"
    - name: "gpt-5.2-codex"
  gemini-cli:
    - name: "gemini-2.5-pro"
    - name: "gemini-3-pro-preview"
    - name: "gemini-2.5-flash"
claude-api-key:
  - api-key: "sk-minimax"
    base-url: "https://api.minimaxi.com/anthropic"
    models:
      - name: "MiniMax-M2.1"
